// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = "https://tmlwyddaogdsntibnxhw.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtbHd5ZGRhb2dkc250aWJueGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2ODc4NzcsImV4cCI6MjA2MDI2Mzg3N30.afyH3B80nOU6hU9lGkrnbIrIS5caorpa7uQpCX9pv90";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);



// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lviadnkeuurcacefcnri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2aWFkbmtldXVyY2FjZWZjbnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4MzY5MTEsImV4cCI6MjA5MjQxMjkxMX0.vHASTZ73LrEpz4dTFyMW351MpSwWXS4QCeDn8TM0OgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);